### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by anaseqal** [ScriptArtist/Scalable#2]
<img width="1187" alt="scalable" src="https://user-images.githubusercontent.com/5034308/29244046-70594530-7fb7-11e7-80a6-ce5b3e3ad865.png">

<img width="704" alt="scalable" src="https://user-images.githubusercontent.com/5034308/29244048-815bafe4-7fb7-11e7-87e0-130196986442.png">

**Comment by ScriptArtist** [comment]
@anaseqal, thank you for founded problem! 
Fixed.
